plugins {
    id 'java'
}

group = 'com'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.rest-assured:rest-assured:6.0.0'
    testImplementation 'org.testng:testng:7.11.0'
    implementation 'tools.jackson.core:jackson-databind:3.0.3'
    implementation 'org.slf4j:slf4j-simple:2.0.17'
    implementation 'io.github.cdimascio:dotenv-java:3.2.0'
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'org.apache.poi:poi:5.2.5'
    implementation 'org.apache.poi:poi-ooxml:5.2.5'

    // Extent Report dependencies
    testImplementation 'com.aventstack:extentreports:5.1.2'
    
    // HTTP Client for Slack integration
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}

test {
    useTestNG() {
        suites 'src/test/resources/testng.xml'
    }

    ignoreFailures = true

    testLogging {
        events "passed", "skipped", "failed"
    }
}